sudo: false

language: java
services:
- docker

jdk:
  - openjdk8

install: ./gradlew --version

env:
  global:
  - version=0.1.0
  - date=$(date +%Y%m%d-%H%M%S)
  - dockerrepo=klibio/io.klib.aries.example
  - commit=`echo "$TRAVIS_COMMIT"|cut -c1-7`
  - dockerversion=${version}.${date}_${commit}

script:
- ./gradlew export.launch --no-daemon
#build image
- docker build -t $dockerrepo:${TRAVIS_BRANCH}_x86-64_$dockerversion -t $dockerrepo:${TRAVIS_BRANCH}_x86-64_latest .
- docker build -t $dockerrepo:${TRAVIS_BRANCH}_arm32v7_$dockerversion -t $dockerrepo:${TRAVIS_BRANCH}_arm32v7_latest -f Dockerfile-arm32v7 .
#login dockerhub & push
- docker login -u $DCKUSR -p $DCKPW
- docker push $dockerrepo:${TRAVIS_BRANCH}_x86-64_$dockerversion
- docker push $dockerrepo:${TRAVIS_BRANCH}_arm32v7_$dockerversion
- docker push $dockerrepo:${TRAVIS_BRANCH}_x86-64_latest
- docker push $dockerrepo:${TRAVIS_BRANCH}_arm32v7_latest
