FROM arm32v7/adoptopenjdk:8-jre-hotspot-bionic

RUN mkdir -p /usr/src/app
COPY io.klib.aries.example/generated/distributions/executable/launch.jar /usr/src/app
WORKDIR /usr/src/app
CMD java -jar launch.jar